server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location = / {
        try_files /index.html =404;
    }

    location = /index.html {
        return 301 /$is_args$args;
    }

    location = /index {
        return 301 /$is_args$args;
    }

    location ~ ^/(.+)\.html$ {
        return 301 /$1$is_args$args;
    }

    location / {
        try_files $uri $uri.html =404;
    }

    location /public/ {
        expires 7d;
        add_header Cache-Control "public";
    }
}
